### PR TITLE
Resolved #54: "buildInfo" should report correct server version.

### LINKED ISSUE #54: "buildInfo" is returning wrong version information
As reported [here](https://forums.foundationdb.org/t/server-reports-as-being-mongo-api-verson-2-4/1079), mongo shell is returning version 2.4.0. We are compatible with 3.0.0 it should return that instead.

The issue is mongo shell depends on `buildInfo` command response to find out version. We are updating `isMaster` but not `buildInfo`. We should change there too.

Note: Not directly related to this, but with `buildInfo` we don't return anything about git hash or branch information, as we are not really MongoDB. So far, that didn't seem to cause any issues, or we didn't notice yet. We do have a custom command `getdoclayerversion` that gives us more information on Document Layer versions.

### PR DESCRIPTION
**Pull request by apkar**

### CODE REVIEW

File: src/Ext.h [hunk 1]
```diff
@@ -26,6 +26,7 @@
 #include "bson.h"
 #include "flow/flow.h"
 
+#define EXT_SERVER_VERSION "3.0.0"
```
Comment (dongxinEric) [inline src/Ext.h]: 👍
